[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.polygon]
eth-rpc-url = 'http://127.0.0.1:10002'
chain-id = 100

[profile.anvil]
eth-rpc-url = 'http://127.0.0.1:8545'
chain-id = 31337
